FROM arm64v8/node:21-bullseye

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY src src
COPY tsconfig.json tsconfig.json
COPY package*.json ./
COPY next.config.mjs next.config.mjs
COPY tailwind.config.ts tailwind.config.ts
COPY postcss.config.mjs postcss.config.mjs
COPY public public

ARG FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
ARG FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
ARG FIREBASE_DATABASEURL
ENV NEXT_PUBLIC_FIREBASE_DATABASEURL=${FIREBASE_DATABASEURL}
ARG FIREBASE_PROJECTID
ENV NEXT_PUBLIC_FIREBASE_PROJECTID=${FIREBASE_PROJECTID}
ARG FIREBASE_STORAGEBUCKET
ENV NEXT_PUBLIC_FIREBASE_STORAGEBUCKET=${FIREBASE_STORAGEBUCKET}
ARG FIREBASE_MESSAGINGSENDERID
ENV NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID=${FIREBASE_MESSAGINGSENDERID}
ARG FIREBASE_APPID
ENV NEXT_PUBLIC_FIREBASE_APPID=${FIREBASE_APPID}
ARG ENV
ENV NEXT_PUBLIC_ENV=${ENV}
ARG API_BASE
ENV NEXT_PUBLIC_API_BASE=${API_BASE}

RUN npm ci
RUN npm run build

ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
# permission denied対策
RUN chown nextjs:nodejs /app/.next/cache

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOST=0.0.0.0
ENV NODE_TLS_REJECT_UNAUTHORIZED=0

ARG FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
ARG FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
ARG FIREBASE_DATABASEURL
ENV NEXT_PUBLIC_FIREBASE_DATABASEURL=${FIREBASE_DATABASEURL}
ARG FIREBASE_PROJECTID
ENV NEXT_PUBLIC_FIREBASE_PROJECTID=${FIREBASE_PROJECTID}
ARG FIREBASE_STORAGEBUCKET
ENV NEXT_PUBLIC_FIREBASE_STORAGEBUCKET=${FIREBASE_STORAGEBUCKET}
ARG FIREBASE_MESSAGINGSENDERID
ENV NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID=${FIREBASE_MESSAGINGSENDERID}
ARG FIREBASE_APPID
ENV NEXT_PUBLIC_FIREBASE_APPID=${FIREBASE_APPID}
ARG ENV
ENV NEXT_PUBLIC_ENV=${ENV}
ARG API_BASE
ENV NEXT_PUBLIC_API_BASE=${API_BASE}

CMD ["npm", "start"]