import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'

export const metadata: Metadata = {
  title: 'Scenario Tuker',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <head>
        <script
          async
          src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-0917187897820609'
          crossOrigin='anonymous'
        ></script>

        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='anonymous'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Sarpanch:wght@400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
      </head>
      <body>
        <Header />
        <div id='portal' className='mx-auto w-full max-w-lg p-2 sm:p-3'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
