import type { Metadata } from 'next'
import './globals.css'
import { Provider } from 'jotai'
import React from 'react'

export const metadata: Metadata = {
  title: 'Scenario Tuker',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <head>
        <script
          async
          src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-0917187897820609'
          crossOrigin='anonymous'
        ></script>

        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='anonymous'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Sarpanch:wght@400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
      </head>
      <body className='text-xs sm:text-sm'>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
